### ISSUE TITLE
Should we make this repo public?

### ISSUE THREAD

**Issue by mattconsto** [mattconsto/lost-the-game#46]
As far as I am aware, development has slowed/halted, so should we make this repo public or keep it private? My plan is to go with the majority vote in a weeks time, unless someone makes a truly convincing argument.

http://strawpoll.me/3619098

Personally I am in favor of making the repo public.

**Comment by mattconsto** [comment]
jemeson007, there is absolutely no way this is going to be ported to Unity and no chance it will ever run on consoles. You contributed nothing during the jam, in other events, (I would love to be proved wrong) and nothing to this since. We don't want you in this team.

Feel free to submit pull requests.

**Comment by agjlewis** [comment]
Heya, Anyways this is turning into a bit of an odd discussion. Unity - Mute point for this game, this game is about being in Java and being from scratch - If we had used unity we would not have done this game full stop :)
(Same argument applies for other platforms)

Back to the repo public Idea - I have been a bit busy recently so haven't been able to contribute as much as I would like. Would public readonly be another option ?

Regards,
Andrew L.

**Comment by mattconsto** [comment]
Read only is the default. In order for someone to commit changes they need to be listed as a contributor or have their pull request approved

**Comment by agjlewis** [comment]
Sounds good to me then :)
(Especially now you guys have improved the repo contents)

**Comment by jemeson007** [comment]
Ollie,
That's fair enough.
I was under the impression that the game will be played by 'others'.
If it's for fun that's one thing, but if you intend to have a market for it
then you might want to consider a business perspective as well.
Had minimal coding participation, does not mean I can't further the group's
agenda for engineering the game in other areas.

Thanks for the heads up though, I already introduced Barry to the team to
help out with coding and I will do more than the sound class on next pull.
That's if you don't mind of course!

Regards,
Jonah Emeson

On 13 Feb 2015 09:06, "Oliver Steptoe" <notifications@github.com> wrote:
>
> What you don't realise is that this is NOT a triple A title. We don't
need to 'target' anything, this is mostly for fun. I'd prefer not to have
to port the entire game because let's face it, it's not going to be you!
You have 2 commits to your name on here for sound that was supposed to be 3
methods. This took you over 24 hours before I took over and implemented it
within 5 minutes. If you'd managed to finish that task you could have moved
onto implementing more features within the game but you seemed more
interested in talking about football on the phone! Why do you think you can
persuade us to take on such a large change when we've seen little to
nothing from you?
